



# 协程与任务

[TOC]

## 协程

协程通过async/await语法进行声明,是编写asyncio应用的推荐方式。

```python
import asyncio

async def main():
    print('hello')
    await asyncio.sleep(1)
    print('world')

asyncio.run(main())

# 输出:
hello
world
```

简单的调用一个协程并不会将其加入执行日程，要真正运行一个协程，asyncio提供了三种主要机制：

* asyncio.run()函数用来运行最高层级的入口点”main()"函数
* 等待一个协程。协程中含有休眠等状态
* asyncio.create_task()函数用来并发运行作为asyncio任务的多个协程。

```python
import asyncio
import time

async def say_after(delay, what):
    await asyncio.sleep(delay)
    print(what)

async def main():
    print(f"started at {time.strftime('%X')}")

    task1 = asyncio.create_task(say_after(1, 'hello'))
    task2 = asyncio.create_task(say_after(2, 'world'))

    await task1
    await task2

    print(f"finished at {time.strftime('%X')}")

asyncio.run(main())

# 输出
started at 14:27:01
hello
world
finished at 14:27:03
```

## 可等待对象

如果一个对象可以在await语句中使用，那么它就是可等待对象。许多asyncio API都被设计为接受可等待对象。

可等待对象欧三种主要类型：协程，任务和Future

**协程**

python谢还吃呢个属于可等待对象，因此可以做其他协程中内等待。

在本文档中 "协程" 可用来表示两个紧密关联的概念:

* 协程函数: 定义形式为async def的函数;
* 协程对象: 调用协程函数所返回的对象。

**任务**

任务被用来设置日程以便并发执行协程

当一个协程通过asyncio.create_task()等函数被打包为一个任务，该协程将自动排入日程准备立即运行

**Future**

Future是一种特殊的底层级可等待对象，表示一个异步操作的最终结果。

当一个 Future 对象被等待，这意味着协程将保持等待直到该 Future 对象在其他地方操作完毕。在 asyncio 中需要 Future 对象以便允许通过 async/await 使用基于回调的代码。通常情况下没有必要在应用层级的代码中创建 Future 对象。

## 运行asyncio程序

asyncio.run(coro, *, debug=False)

> 执行coroutine coro 并返回结果
>
> 此函数运行传入的协程，负责管理 asyncio 事件循环并 完结异步生成器。
>
> 当有其他 asyncio 事件循环在同一线程中运行时，此函数不能被调用。
>
> 如果debug为True，事件循环将以调试模式运行。
>
> 此函数总是会创建一个新的事件循环并在结束时关闭之。它应当被用作 asyncio 程序的主入口点，理想情况下应当只被调用一次。

```python
# 示例:
async def main():
    await asyncio.sleep(1)
    print('hello')

asyncio.run(main())
```

## 创建任务

asyncio.create_task(coro, *, name=None)

> 将coroutine coro打包为一个Task排入日程准备执行。返回 Task 对象。
>
> name不为None，它将使用Task.set_name()来设为任务的名称。
>
> 该任务会在get_running_loop()返回的循环中执行，如果当前线程没有在运行的循环则会引发RuntiomeError。

```python
async def coro():
    ...

# 在Python3.7+
task = asyncio.create_task(coro())

# 在python3.7之前的版本
task = asyncio.ensure_future(coro())
```

## 休眠

coroutine  asyncio.sleep(delay, result=None, *, loop=None)

> 阻塞delay指定的秒数
>
> 如果指定了result,则当协程完成是将其返回给调用者
>
> sleep()总是会挂起当前任务，以允许其他任务运行

```python
import asyncio
import datetime

async def main():
    for i in range(5):
        print(datetime.datetime.now())
        await asyncio.sleep(1)

asyncio.run(main())
```

## 并发运行任务

awaitable  asyncio.gather(*aws, lopp=None, return_exceptions=False)

> 并发运行aws序列中的可等待对象
>
> 如果aws中的某个可等待对象为协程，它将自动作为一个任务加入日程。
>
> 如果所有可等待对象都成功完成，结果将是一个由所有返回值聚合而成的列表。结果值的顺序与aws中可等待对象的顺序一致。
>
> 如果return_exceptions为False(默认)，所引发的首个异常会立即传播给等待gather()的任务。aws序列中的其他可等待对象不会被取消并讲继续运行
>
> 如果return_exceptions为True,异常会和成功的结果一样处理，并聚合至结果列表。
>
> 如果gather()被取消，所有被提交 (尚未完成) 的可等待对象也会 *被取消*。
>
> 如果aws序列中的任一 Task 或 Future 对象被取消，它讲被当做引发了CancelledError一样处理--在此轻快下gather()调用不会被取消。这是为了防止一个已提交的Task/Future被取消导致其他Tasks/Future也被取消。

```python
import asyncio

async def factorial(name, number):
    print(10 / number)
    f = 1
    for i in range(2, number + 1):
        print(f"Task {name}: Compute factorial({i})...")
        await asyncio.sleep(1)
        f *= i
    print(f"Task {name}: factorial({number}) = {f}")

async def main():
    # Schedule three calls *concurrently*:
    await asyncio.gather(
        factorial("A", 2),
        factorial("B", 3),
        factorial("C", 4),
    )

asyncio.run(main())
```

```
注意
如果 return_exceptions 为 False，则在 gather() 被标记为已完成后取消它将不会取消任何已提交的可等待对象。 例如，在将一个异常传播给调用者之后，gather 可被标记为已完成，因此，在从 gather 捕获一个（由可等待对象所引发的）异常之后调用 gather.cancel() 将不会取消任何其他可等待对象。
```

## 屏蔽取消操作

awitable  asyncio.shield(aw, *, loop=None)

> 保护一个可等待对象防止其被取消
>
> 如果aw是一个协程，它将自动作为任务加入日程
>
> 以下语句：

```Python
res = await shield(something())
```

> 相当于：

```
res = await something()
```

> 不同之处在于如果包含它的协程被取消，在 something() 中运行的任务不会被取消。从 something() 的角度看来，取消操作并没有发生。然而其调用者已被取消，因此 "await" 表达式仍然会引发 CancelledError。
>
> 如果通过其他方式取消 something() (例如在其内部操作) 则 shield() 也会取消。
>
> 如果希望完全忽略取消操作 (不推荐) 则 shield() 函数需要配合一个 try/except 代码段，如下所示:

```python
try:
    res = await shield(something())
except CancelledError:
    res = None
```

## 超时

coroutine  asyncio.wait_for(aw, timeout, *, loop=None)

> 等待aw可等待对象完成，指定timeout秒数后超时
>
> 如果aw是一个协程，它将自动作为任务加入日程
>
> timeout可以为None,也可以为 float 或 int 型数值表示的等待秒数。如果timeout为None,则等待直到完成
>
> 如果发生超时，任务将取消并引发asyncio.TimeoutError
>
> 要避免任务取消，可以加上shield()
>
> 函数将等待直到目标对象确实被取消，所以总等待时间可能超过 timeout 指定的秒数。
>
> 如果等待被取消，则 aw 指定的对象也会被取消。

```python
import asyncio

async def eternity():
    # Sleep for one hour
    await asyncio.sleep(3600)
    print('yay!')

async def main():
    # Wait for at most 1 second
    try:
        await asyncio.wait_for(eternity(), timeout=1.0)
    except asyncio.TimeoutError:
        print('timeout!')

asyncio.run(main())
```

## 简单等待

coroutine  asyncio.wait(aws, *, loop=None, timeout=None, return_when=ALL——COMPLETED)

> 并发运行aws指定的可等待对象并阻塞县城直到满足reurn_when指定的条件
>
> 返回两个Task/Future集合：（done, pending）
>
> 用法

```python
done, pending = await asyncio.wait(aws)
```

> 如指定timeout（float或int类型）则它将被用于控制返回之前等待的最长秒数
>
> 请注意此函数不会引发 asyncio.TimeoutError。当超时发生时，未完成的 Future 或 Task 将在指定秒数后被返回。
>
> return_when 指定此函数应在何时返回。它必须为以下常数之一:

| 常数            | 描述                                                         |
| :-------------- | :----------------------------------------------------------- |
| FIRST_COMPLETED | 函数将在任意可等待对象结束或取消时返回。                     |
| FIRST_EXCEPTION | 函数将在任意可等待对象因引发异常而结束时返回。当没有引发任何异常时它就相当于 ALL_COMPLETED。 |
| ALL_COMPLETED   | 函数将在所有可等待对象结束或取消时返回。                     |

> 与wait_for() 不同，wait()在超时发生时不会取消可等待对象。
>
> 3.8版本后已移除：如果aws中的某个可等待对象为协程，它将自动作为任务加入日程。直接向wait()传入协程对象已经弃用。

> wait()会自动将协程作为任务加入日程，以后将以(done, pending)集合形式返回显式创建的任务对象。因此以下代码并不会有预期的行为：

```python
async def foo():
    return 42

coro = foo()
done, pending = await asyncio.wait({coro})

if coro in done:
    # This branch will never be run!
```

> 以上代码段的修正方法如下：

```python
async def foo():
    return 42

task = asyncio.create_task(foo())
done, pending = await asyncio.wait({task})

if task in done:
    # Everything will work as expected now.
```

asyncio.as_completed(aws, *, loop=None, timeout=None)

> 并发地运行 *aws* 集合中的可等待对象。返回一个协程的迭代器。所返回的每个协程可被邓丹以从剩余的可等待对象集合中活的最早的下一个结果。
>
> 如果在所有 Future 对象完成前发生超时则将引发asyncio.TimeoutError.

```
for coro in as_completed(aws):
    earliest_result = await coro
    # ...
```

## 来自其他线程的日程安排

asyncio.run_coroutine_threadsafe(coro, loop)

> 向指定事件循环提交一个协程。线程安全。
>
> 返回一个concurrent.futures.Future以等待来自其他OS线程的结果。
>
> 此函数应该从另一个OS线程中调用，而非事件循环运行所在县城，

```python
# Create a coroutine
coro = asyncio.sleep(1, result=3)

# Submit the coroutine to a given 
future = asyncio.run_coroutine_threadsafe(coro, loop)

# Wait for the result with an optional timeout argument
assert future.result(timeout) == 3
```

> 如果在协程内产生了异常，将会通知返回的Future对象。它也可被用来取消事件循环中的任务

```python
try:
    result = future.result(timeout)
except asyncio.TimeoutError:
    print('The coroutine took too long, cancelling the task...')
    future.cancel()
except Exception as exc:
    print(f'The coroutine raised an exception: {exc!r}')
else:
    print(f'The coroutine returned: {result!r}')
```

> 不同与其他 asyncio 函数，此函数要求显式地传入 *loop* 参数。

## 内省

asyncio.current_task(loop=None)

> 返回当前运行的Task实例，如果没有正在运行的任务则返回None
>
> 如果loop为None则会使用get_running_loop()获取当前事件循环

asyncio.all_tasks(loop=None)

> 返回事件循环所运行的未完成的Task对象的集合
>
> 如果loop为None，则会使用get_running_loop()互殴去当前事件循环

## Task对象

class asyncio.Task(coro, *, loop=None, name)

> 一个与Future类似的对象，可运行Python协程。非线程安全。
>
> Task 对象被用来在事件循环中运行协程。如果一个协程在等待一个 Future 对象，Task 对象会挂起该协程的执行并等待该 Future 对象完成。当该 Future 对象 *完成*，被打包的协程将恢复执行。
>
> 事件循环使用协同日程调度: 一个事件循环每次运行一个 Task 对象。而一个 Task 对象会等待一个 Future 对象完成，该事件循环会运行其他 Task、回调或执行 IO 操作。
>
> 使用高层级的asyncio.create_task()函数来创建Task对象，也可用低层级的loop.create_task()或ensure_future()函数。不建议手动实例化 Task 对象。
>
> 要取消一个正在运行的 Task 对象可使用cancel()方法。调用此方法将使该 Task 对象抛出一个CancelledError异常给打包的协程。如果取消期间一个协程正在等待一个 Future 对象，该 Future 对象也将被取消。
>
> cancelled()可被用来检测 Task 对象是否被取消。如果打包的协程没有抑制CancelledError异常并且确实被取消，该方法将返回True
>
> asyncio.Task从Future继承了其除Future.set_result()和Future.set_exception()以外的所有API
>
> Task对象支持contextvars模块。当一个Task对象被创建，它将复制当前上下文，然后在复制的上下文中运行其协程
>
> 在3.7版加入对contextvars模块的支持
>
> 在3.8版添加了name形参

**cancel()**

> 请求取消Task对象。
>
> 这将安排在下一轮事件循环中抛出一个CancelledError异常给被封包的协程。
>
> 协程在之后有机会进行清理甚至使用try ... ... except CancelledError ... finally代码块抑制异常来拒绝请求。不同于Future.cancel(),Task.cancel()不保证 Task 会被取消，虽然抑制完全取消并不常见，也很不鼓励这样做。
>
> 以下示例演示了协程是如何侦听取消请求的:

```python
async def cancel_me():
    print('cancel_me(): before sleep')

    try:
        # Wait for 1 hour
        await asyncio.sleep(3600)
    except asyncio.CancelledError:
        print('cancel_me(): cancel sleep')
        raise
    finally:
        print('cancel_me(): after sleep')

async def main():
    # Create a "cancel_me" Task
    task = asyncio.create_task(cancel_me())

    # Wait for 1 second
    await asyncio.sleep(1)

    task.cancel()
    try:
        await task
    except asyncio.CancelledError:
        print("main(): cancel_me is cancelled now")

asyncio.run(main())

# Expected output:
#
#     cancel_me(): before sleep
#     cancel_me(): cancel sleep
#     cancel_me(): after sleep
#     main(): cancel_me is cancelled now
```

**cancelled()**

> 如果Task对象被取消则返回True
>
> 当使用cancel()发出取消请求时Task会被取消，其封包的协程将传播被抛入的CancelledError异常

**done()**

> 如果Task对象已完成则返回True
>
> 当Task所封包的协程返回一个值、引发一个异常或 Task 本身被取消时，则会被认为 已完成。

**result()**

> 返回 Task 的结果。
>
> 如果 Task 对象 已完成，其封包的协程的结果会被返回 (或者当协程引发异常时，该异常会被重新引发。)
>
> 如果 Task 对象 *被取消*，此方法会引发一个CancelledError异常
>
> 如果 Task 对象的结果还不可用，此方法会引发一个InvalidStateError异常

**exception()**

> 回 Task 对象的异常。
>
> 如果所封包的协程引发了一个异常，该异常将被返回。如果所封包的协程正常返回则该方法将返回None
>
> 如果 Task 对象 *被取消*，此方法会引发一个CancelledError异常
>
> 如果 Task 对象尚未 *完成*，此方法将引发一个InvalidStateError异常

**add_done_callback(callback, \*, context=None)**

> 添加一个回调，将在 Task 对象 完成*时被运行。
>
> 此方法应该仅在低层级的基于回调的代码中使用。

**remove_done_callback(callback)**

>回调列表中移除 callback 。
>
>此方法应该仅在低层级的基于回调的代码中使用。

**get_stack(\*, limit=None)**

> 返回此 Task 对象的栈框架列表。
>
> 如果所封包的协程未完成，这将返回其挂起所在的栈。如果协程已成功完成或被取消，这将返回一个空列表。如果协程被一个异常终止，这将返回回溯框架列表。
>
> 框架总是从按从旧到新排序。
>
> 每个被挂起的协程只返回一个栈框架。
>
> 可选的 *limit* 参数指定返回框架的数量上限；默认返回所有框架。返回列表的顺序要看是返回一个栈还是一个回溯：栈返回最新的框架，回溯返回最旧的框架。(这与 traceback 模块的行为保持一致。)

**print_stack(\*, limit=None,file=None)**

> 打印此 Task 对象的栈或回溯。
>
> 此方法产生的输出类似于 traceback 模块通过get_stack()所获取的框架。
>
> limit参数会直接传递给get_stack()
>
> file参数是输出所写入的 I/O 流；默认情况下输出会写入sys.stderr

**get_coro()**

> 返回由Task包装的协程对象

**get_name()**

> 返回Task的名称
>
> 如果没有一个 Task 名称被显式地赋值，默认的 asyncio Task 实现会在实例化期间生成一个默认名称。

**set_name(value)**

> 设置 Task 的名称。
>
> value 参数可以为任意对象，它随后会被转换为字符串。
>
> 在默认的 Task 实现中，名称将在任务对象的 repr()输出中可见。

**classmethod all_tasks(loop=None)**

> 返回一个事件循环中所有任务的集合。
>
> 默认情况下将返回当前事件循环中所有任务。如果 *loop* 为 None，则会使用get_event_loop()函数来获取当前事件循环。
>
> Deprecated since version 3.7, will be removed in version 3.9: 请不要将此方法作为任务方法来调用。 应当改用 asyncio.all_tasks() 函数。

**classmethod current_task(loop=None)**

> 返回当前运行任务或 None。
>
> 如果 *loop* 为 None，则会使用 get_event_loop()函数来获取当前事件循环。
>
> Deprecated since version 3.7, will be removed in version 3.9:请不要将此方法作为任务方法来调用。 应当改用 asyncio.current_task() 函数。